### ISSUE TITLE
Possible to remove the "Q"-Units from the project?

### ISSUE THREAD

**Issue by CodehunterWorks** [SynEdit/SynEdit#113]
Hello!

I'm was part of the SynEdit project on SF for a while. And at this time I'm ask myself often, why we have the "Q"-Units in the project. The only reason for that was compatibility to CLX for Kylix. Is there any Kylix related today? If not, its a simple job for refactoring.

Greets
Cody

**Comment by CWBudde** [comment]
In my opinion, it would make sense to store the current state as branch and go on without the Q units in the master. Especially, since it is now again possible to compile for Linux without the need of the Q units. But that's just my opinion (but I don't want to do the job).

**Comment by CodehunterWorks** [comment]
When you add me to the project, I will do the job next weekend. If so, its important to check in all open work before to avoid conflicts, because this change will affect nearly all units in the project.

**Comment by CWBudde** [comment]
I granted you member rights, so you should be able to commit code to the main repository directly. I didn't gave you admin rights right now, because it is not really "my" project. In my opinion it would make sense to ask the other admins if this is OK before. Beside, there is currently no real need to have more admins.

Anyway, thanks for taking this effort.

**Comment by CodehunterWorks** [comment]
This is ok to me because I haven't enough time to do an further admin job. But smaller tasks are no problem and there are some ideas and existing improvements to some highlighters in my "code cellar"

@partouf @Arvur @vincentparrett @atlant2011

**Comment by CodehunterWorks** [comment]
Further question: Is SynEdit generally tested against Kylix or Linux these days? As i can see, at some points we set IFDEF Linux and mean the OLDGEN compiler. Today we have a DEFINE Linux also but mean the NEXTGEN compiler since 10.1 Berlin Enterprise.

Simple question: Can and would we drop support for Kylix and OLDGEN Linux compiler? I think this a good idea for potentially support NEXTGEN Linux compiler in the future. Remember there is VCL4Linux. But I think in theory we can't compile here because wrong old compiler switches in the .INCs (I cannot test it, I haven't DXE)

@EricGrange @romankassebaum @CWBudde

**Comment by krisjace** [comment]
Are Qunits only specific to Kylix? What about Lazarus? Please remember that SynEdit is an important component on Lazarus, and including Linux targets, both desktop and mobile.

**Comment by CWBudde** [comment]
I have now removed the Q* units from the master branch (as well as the unfinished DirectWrite code). Both are still available in dedicated branches ('Kylix' and 'DirectWrite').

Neither Kylix nor Lazarus compatibility is officially supported anymore (Kylix, because there seems to be no-one still using it and Lazarus has never been officially supported by this SynEdit project. Lazarus maintains its own fork).
