### ISSUE TITLE
Highlighter for Javascript ES6

### ISSUE THREAD

**Issue by khongten001** [SynEdit/SynEdit#153]
Hi,

Is there any chance to get JS highlighter supports ES6 keyword and multi-line string? Ex: import...from...let, of...

**Comment by CWBudde** [comment]
The fastest way is to do it by yourself. That is:
1. fork this repository
2. make the necessary changes
3. test your changes with various source files
4. commit the changes to your fork
5. create a pull request
6. (our part) -> merge the pull request with the main repository

If the required changes are small, the chances are high that we can have this by the end of the day. If the changes are bigger, it's probably more difficult to do, test and review from our side. This said it might take days/weeks.

If you can't / won't do the changes yourself, we put this on the to do list and implement it as soon as there is some spare time for this (right now at least my time is very limited due to the corona limitations which causes extra difficulties during the normal life).

**Comment by CWBudde** [comment]
I have started a new ECMA Script highlighter that should comply to the latest ECMA-262 standard (edition 11 from 2020). I haven't tested it in great detail so far, but it should work stable enough, while offering a more modern highlighting.

**Comment by khongten001** [comment]
Thank you for adding ECMA Script highlighter :)
