### ISSUE TITLE
New releases?

### ISSUE THREAD

**Issue by Memnarch** [SynEdit/SynEdit#37]
Right now this project seems to be in a fluid development state. However i'd appreciate releases to see which states are considered stable to avoid "In Development" states in Production code.

**Comment by uschuster** [comment]
I for myself have no plans for any releases. I do work since a while on a code editing project and I fixed for example the hints or the (code completion) demo issues because they bugged me (too). What I could do is adding significant changes to Readme.md like the demo fixes or the OnSpecialTokenAttributes event.
(BTW, ChangeLog.htm seems to be very outdated. The newest release in there is 1.04, but IIRC the latest release was 2.08)

**Comment by Memnarch** [comment]
The reason for releses is having something to build against for a production environment. I don't want to note the commithash somewhere ;)

**Comment by uschuster** [comment]
I have made a compromise - I have published a release and marked it as pre-release.

https://github.com/SynEdit/SynEdit/releases/tag/SynEdit-2.0.9-beta

**Comment by CWBudde** [comment]
Personally I don't care much for stable releases. I prefer more to work on the latest edge and to keep everything in flux (like the HTML5 standard).
This said, I like the fact that we have a release that is kind of written in stone, so that users can be sure to have something that is quite stable. Especially those who don't have time to follow the development.

**Comment by Memnarch** [comment]
@uschuster thanks
@CWBudde  That's NOT how production works. How many people work on your team? How large is the product you integrated a thirdparty component into?

**Comment by CWBudde** [comment]
With "personally" I rather meant my personal pet projects on which I work alone. All projects for customers use fixed (read it as "stable") revisions. However, in many cases no such revisions are tagged as such, so these are too often cherry picked.
However, when working with HTML5 and such, one can't rely much on something that is declared "stable". Even in a "stable" state it could easily break when the specs changed. And they do so constantly.
