### ISSUE TITLE
TSynBaseCompletionProposalForm incomplete BackgroundColor

### ISSUE THREAD

**Issue by Memnarch** [SynEdit/SynEdit#39]
Today i changed the Backgroundcolor of the SynCompletionProposal. However a one line rect around was left with clBtnFace. Looking into SynCompletionProposal.pas

`[1657]Canvas.Pen.Color := clBtnFace;`
This is hardcoded. I used a dark color like in VS2015 DarkTheme for the Background and the rectangle is way to visible. However i can not change it by using a property.

EDIT: Ofcourse i can use OnPaintItem and do a FillRect first. But this seems to be avoidable overdraw.

**Comment by uschuster** [comment]
The new property ClBackgroundBorder should be sufficient to fix the issue.

**Comment by Memnarch** [comment]
looks good. I just don't understand why you extended GetCLBack with an index?

**Comment by uschuster** [comment]
Because an index specifier is now used for the properties ClBackground and ClBackgroundBorder to share the access methods between both to avoid adding another pair of GetColorX and SetColorX methods.

GetClBack and SetClBack were and are private methods. Since reading and writing TSynBaseCompletionProposal.ClBackground does the same like calling GetClBack and SetClBack there is no use case for calling these methods directly and thatswhy the signature can be changed. This is a non-breaking change.

All Cl color properties could share the same read function and the same write procedure, but the more code you change the higher is the risk of regression. The far better option would be to use a class inherited from TPersistent to store the colors, but that would be a breaking change.
