### ISSUE TITLE
TSynGeneralSyn.StringDelim bug

### ISSUE THREAD

**Issue by JeffCardozo** [SynEdit/SynEdit#64]
I'm using TSynGeneralSyn to create my language, but I'm having a problem with the StringDelim property. When there is a line break, the editor understands that the string has also terminated.
![synedit](https://cloud.githubusercontent.com/assets/29045432/26580024/b3237b5a-450c-11e7-9614-78e635b0bc39.png)

**Comment by CWBudde** [comment]
You must specify that strings are multi line strings as otherwise the string is automatically terminated at the end of the line.
This said, I'm not sure whether this is possible with the TSynGeneralSyn script at all. I'll have a look at this in the next days. Not sure though if this is easy to fix.

Eventually you must write your own highlighter to solve this more deeply. Actually, it's not that complicated.

**Comment by CWBudde** [comment]
Ok, I got a closer look now and it seems that the property StringMultiLine is declared as public and not published. Unfortunately, it's not only not accessible from the object inspector, but also working as expected. 
I'll have a deeper look into this, but maybe not today.

**Comment by JeffCardozo** [comment]
I saw this property, tried to work with it forcing the assignment to a true value but apparently it is not used inside the code and so may not be published.

**Comment by CWBudde** [comment]
I just patched the code for the string multiline from another syntax highlighter. Not sure whether it is 100% safe as I ran into a few issues during development, but it seems to be working at least in this case.
